const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.destroy,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Plateforme: 0},
	{DéfilerVers: 0},
	{"8Directions": 0},
	{DestroyOutside: 0},
	{Player: 0},
	{Solide: 0},
	{collison: 0},
	{Souris: 0},
	{Clavier: 0},
	{saws: 0},
	{Ncollision: 0},
	{decoratif: 0},
	{Ladder: 0},
	{key: 0},
	{door: 0},
	{Spike: 0},
	{levier: 0},
	{light: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{lightTorch: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Particules: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Navigateur: 0},
	{Texte: 0},
	{Sprite10: 0},
	{PortableKey: 0},
	{Toucher: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	collison: class extends self.ITilemapInstance {},
	Souris: class extends self.IInstance {},
	Clavier: class extends self.IInstance {},
	saws: class extends self.ISpriteInstance {},
	Ncollision: class extends self.ITilemapInstance {},
	decoratif: class extends self.ITilemapInstance {},
	Ladder: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	levier: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	lightTorch: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Particules: class extends self.IParticlesInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Navigateur: class extends self.IInstance {},
	Texte: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	PortableKey: class extends self.ISpriteInstance {},
	Toucher: class extends self.IInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}